from django.utils.translation import ugettext_lazy as _

# SET ACCOUNT TYPES
# BALANCE SHEET ACCOUNTS
ASSETS_CASH = 1
ASSETS_ACCOUNTS_RECEIVABLE = 2
ASSETS_EQUIPMENT = 3
ASSETS_INVENTORY = 4
ASSETS_PREPAID_EXPENSES = 5

LIABILITES_ACCOUNTS_PAYABLE = 6
LIABILITES_ACCRUED_EXPENSES = 7
LIABILITES_NOTES_PAYABLE = 8
LIABILITIES_UNEARNED_REVENUE = 9
LIABILITES_DEFERRED_TAXES = 10
LIABILITES_DEFERRED_PAYMENTS = 11

OWNERS_EQUITY_CAPITAL = 12
OWNERS_EQUITY_RETAINED_EARNINGS = 13

# INCOME STATEMENT ACCOUNTS
# INCOME
REVENUE_INCOME = 14

# EXPENSES
EXPENSE_SALARIES = 15
EXPENSE_COST_OF_SALES = 16
EXPENSE_DEPRECATION = 17
EXPENSE_RENT = 18
EXPENSE_INTEREST = 19

# Transaction Types
TRANSACTION_TYPE_GENERAL = 'General'
TRANSACTION_TYPE_POS = 'POS'

TRANSACTION_TYPE_CHOICES=(
    (TRANSACTION_TYPE_GENERAL, TRANSACTION_TYPE_GENERAL),
    (TRANSACTION_TYPE_POS, TRANSACTION_TYPE_POS)
)

# Transaction Statusses:

TRANSACTION_PENDING = 'Pending'
TRANSACTION_POSTED = 'Posted'

TRANSACTION_STATUS_CHOICES = (
        (TRANSACTION_POSTED, TRANSACTION_POSTED),
        (TRANSACTION_PENDING, TRANSACTION_PENDING)
)
